# Generated by Django 4.1.6 on 2023-02-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together={("user", "listing")},
        ),
    ]
