# Generated by Django 4.1.6 on 2023-02-17 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_watchlist_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watching",
            field=models.ManyToManyField(
                blank=True, related_name="watching", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bid",
            unique_together={("user", "item")},
        ),
        migrations.DeleteModel(
            name="Watchlist",
        ),
    ]
