# Generated by Django 4.1.6 on 2023-02-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_watching_alter_bid_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bid",
            unique_together=set(),
        ),
    ]
